# Bundestagswahl 2021: Wahlkreisdaten Schritt für Schritt aufbereiten

Dieses Notebook zeigt jeden Verarbeitungsschritt offen. Die eigentliche Rechenlogik liegt in kleinen Python-Funktionen, aber keine große Pipeline wird als Blackbox aufgerufen.

Die Wahlbezirksdatei wird zuerst geprüft und anschließend auf Wahlkreise zusammengefasst. Die repräsentative Statistik liefert nur Verteilungen auf Landesebene. Ihre gerundeten absoluten Werte werden deshalb in Anteile umgerechnet und später auf die amtlichen Stimmen aus der Wahlbezirksdatei angewendet.

Die Quellkategorie `m` enthält laut Hinweis der Bundeswahlleitung auch Personen mit dem Geschlechtsmerkmal divers sowie Personen ohne Geschlechtseintrag im Geburtenregister.

## 0. Arbeitsverzeichnis und lokale Dateien

In [1]:
from pathlib import Path
import sys
from dataclasses import asdict

import pandas as pd
from IPython.display import display


def find_repository_root() -> Path:
    for candidate in (Path.cwd(), *Path.cwd().parents):
        if (candidate / "scripts").is_dir() and (candidate / "package.json").is_file():
            return candidate
    raise RuntimeError("Das Notebook muss innerhalb des Repository-Ordners laufen.")


ROOT = find_repository_root()
sys.path.insert(0, str(ROOT))
ROOT

PosixPath('/home/nomikron/WebstormProjects/mach-dir-dein-bundestag')

In [2]:
# Diese Namen sind nur lokale Vorschläge. Trage hier die tatsächlich
# heruntergeladenen CSV-Dateien ein.
DISTRICT_RESULTS_CSV = ROOT / "scripts/data/btw21_wbz_ergebnisse.csv"
STATE_DEMOGRAPHICS_CSV = ROOT / "scripts/data/btw21_rws_bst2.csv"
FEDERAL_METHOD_DEMOGRAPHICS_CSV = None  # optionaler lokaler Pfad
OUTPUT_DIRECTORY = ROOT / "scripts/data/generated"

DISTRICT_RESULTS_CSV, STATE_DEMOGRAPHICS_CSV, FEDERAL_METHOD_DEMOGRAPHICS_CSV

(PosixPath('/home/nomikron/WebstormProjects/mach-dir-dein-bundestag/scripts/data/btw21_wbz_ergebnisse.csv'),
 PosixPath('/home/nomikron/WebstormProjects/mach-dir-dein-bundestag/scripts/data/btw21_rws_bst2.csv'),
 None)

In [3]:
from scripts.election_data.btw2021 import read_local_csv
from scripts.election_data.notebook_steps import (
    aggregate_to_constituencies,
    calculate_demographic_profiles,
    calculate_federal_method_weights,
    district_party_columns,
    inspect_district_rows,
    normalize_district_rows,
    normalize_federal_method_rows,
    normalize_state_statistic_rows,
    reshape_federal_method_votes,
    reshape_polling_district_votes,
    reshape_state_statistic_votes,
    select_federal_method_detail_rows,
    select_state_statistic_detail_rows,
    select_usable_district_rows,
)
from scripts.election_data.pipeline import distribute_district_votes, write_vote_entries
from scripts.election_data.profiles import build_state_method_profiles
from scripts.election_data.validation import validate_vote_entries

## 1. Wahlbezirksdatei unverändert einlesen

Zuerst wird nur gelesen. Noch wird keine Zeile entfernt und keine Spalte umbenannt.

In [4]:
raw_districts = read_local_csv(DISTRICT_RESULTS_CSV)
print(f"Zeilen: {len(raw_districts):,}")
print(f"Spalten: {len(raw_districts.columns):,}")
display(raw_districts.head())
display(raw_districts.tail())

Zeilen: 96,300
Spalten: 107

,Wahlkreis,Land,Regierungsbezirk,Kreis,Verbandsgemeinde,Gemeinde,Kennziffer Urnenwahlbezirke nach § 68 BWO,Kennziffer Briefwahlzugehörigkeit,Gemeinde Name,Wahlbezirk,...,Z_Bündnis21,Z_LIEBE,Z_LKR,Z_PdF,Z_LfK,Z_SSW,Z_Team Todenhöfer,Z_UNABHÄNGIGE,Z_Volt,Ungekürzte Wahlbezirksbezeichnung
0,001,01,0,01,0000,000,0000,00,"Flensburg, Stadt",01,...,0,0,0,0,0,118,5,0,1,01
1,001,01,0,01,0000,000,0000,00,"Flensburg, Stadt",02,...,0,0,0,0,0,130,13,0,3,02
2,001,01,0,01,0000,000,0000,00,"Flensburg, Stadt",03,...,0,0,0,0,0,106,4,0,0,03
3,001,01,0,01,0000,000,0000,00,"Flensburg, Stadt",04,...,0,0,0,0,0,84,6,0,0,04
4,001,01,0,01,0000,000,0000,00,"Flensburg, Stadt",05,...,0,0,0,0,0,50,3,0,1,05

,Wahlkreis,Land,Regierungsbezirk,Kreis,Verbandsgemeinde,Gemeinde,Kennziffer Urnenwahlbezirke nach § 68 BWO,Kennziffer Briefwahlzugehörigkeit,Gemeinde Name,Wahlbezirk,...,Z_Bündnis21,Z_LIEBE,Z_LKR,Z_PdF,Z_LfK,Z_SSW,Z_Team Todenhöfer,Z_UNABHÄNGIGE,Z_Volt,Ungekürzte Wahlbezirksbezeichnung
96295,,,,,,,,,,,...,,,,,,,,,,
96296,,,,,,,,,,,...,,,,,,,,,,
96297,,,,,,,,,,,...,,,,,,,,,,
96298,,,,,,,,,,,...,,,,,,,,,,
96299,,,,,,,,,,,...,,,,,,,,,,

## 2. Wahlkreisnummern prüfen

Bevor `Wahlkreis` in eine Ganzzahl umgewandelt wird, werden alle Zeilen eingeteilt:

- `usable`: enthält eine normale Wahlkreisnummer;
- `missing`: leerer Wert oder eine leere Abschlusszeile;
- `invalid`: nicht leer, aber keine Zahl. Solche Zeilen müssen untersucht werden.

Dadurch ist bei einem Fehler direkt sichtbar, welche Quellzeilen ihn verursachen.

In [5]:
district_row_diagnostics = inspect_district_rows(raw_districts)
display(district_row_diagnostics["status"].value_counts().rename("rows"))

problematic_district_rows = district_row_diagnostics[
    district_row_diagnostics["status"] != "usable"
]
display(problematic_district_rows)

status
usable     94668
missing     1632
Name: rows, dtype: int64

,sourceRow,Wahlkreis,Land,Gemeinde Name,Wahlbezirk,Bezirksart,districtIdCandidate,status
94668,94668,,,,,,<NA>,missing
94669,94669,,,,,,<NA>,missing
94670,94670,,,,,,<NA>,missing
94671,94671,,,,,,<NA>,missing
94672,94672,,,,,,<NA>,missing
...,...,...,...,...,...,...,...,...
96295,96295,,,,,,<NA>,missing
96296,96296,,,,,,<NA>,missing
96297,96297,,,,,,<NA>,missing
96298,96298,,,,,,<NA>,missing
96299,96299,,,,,,<NA>,missing

Jetzt werden nur die zuvor sichtbaren leeren Zeilen entfernt. Nicht leere, ungültige Werte führen weiterhin zu einem Fehler mit den konkreten Quellzeilen.

In [6]:
usable_district_rows = select_usable_district_rows(
    raw_districts,
    district_row_diagnostics,
)
print(f"Verwendete Zeilen: {len(usable_district_rows):,}")
display(usable_district_rows.head())

Verwendete Zeilen: 94,668

,Wahlkreis,Land,Regierungsbezirk,Kreis,Verbandsgemeinde,Gemeinde,Kennziffer Urnenwahlbezirke nach § 68 BWO,Kennziffer Briefwahlzugehörigkeit,Gemeinde Name,Wahlbezirk,...,Z_Bündnis21,Z_LIEBE,Z_LKR,Z_PdF,Z_LfK,Z_SSW,Z_Team Todenhöfer,Z_UNABHÄNGIGE,Z_Volt,Ungekürzte Wahlbezirksbezeichnung
0,001,01,0,01,0000,000,0000,00,"Flensburg, Stadt",01,...,0,0,0,0,0,118,5,0,1,01
1,001,01,0,01,0000,000,0000,00,"Flensburg, Stadt",02,...,0,0,0,0,0,130,13,0,3,02
2,001,01,0,01,0000,000,0000,00,"Flensburg, Stadt",03,...,0,0,0,0,0,106,4,0,0,03
3,001,01,0,01,0000,000,0000,00,"Flensburg, Stadt",04,...,0,0,0,0,0,84,6,0,0,04
4,001,01,0,01,0000,000,0000,00,"Flensburg, Stadt",05,...,0,0,0,0,0,50,3,0,1,05

## 3. Wahlkreis, Bundesland und Wahlart vereinheitlichen

Die Wahlkreisnummer wird jetzt zu `districtId`. Die Landeskennziffer wird zum ausgeschriebenen Bundesland. Die Bezirksarten werden für die App auf `postal` und `in-person` abgebildet.

In [7]:
normalized_district_rows = normalize_district_rows(usable_district_rows)

display(
    normalized_district_rows[
        ["Wahlkreis", "districtId", "Land", "state", "Bezirksart", "electionMethod"]
    ].head(20)
)
display(normalized_district_rows["electionMethod"].value_counts())

   Wahlkreis  districtId Land               state Bezirksart electionMethod
0        001           1   01  Schleswig-Holstein          0      in-person
1        001           1   01  Schleswig-Holstein          0      in-person
2        001           1   01  Schleswig-Holstein          0      in-person
3        001           1   01  Schleswig-Holstein          0      in-person
4        001           1   01  Schleswig-Holstein          0      in-person
5        001           1   01  Schleswig-Holstein          0      in-person
6        001           1   01  Schleswig-Holstein          0      in-person
7        001           1   01  Schleswig-Holstein          0      in-person
8        001           1   01  Schleswig-Holstein          0      in-person
9        001           1   01  Schleswig-Holstein          0      in-person
10       001           1   01  Schleswig-Holstein          0      in-person
11       001           1   01  Schleswig-Holstein          0      in-person
12       001           1   01  Schleswig-Holstein          0      in-person
13       001           1   01  Schleswig-Holstein          0      in-person
14       001           1   01  Schleswig-Holstein          0      in-person
15       001           1   01  Schleswig-Holstein          0      in-person
16       001           1   01  Schleswig-Holstein          0      in-person
17       001           1   01  Schleswig-Holstein          0      in-person
18       001           1   01  Schleswig-Holstein          0      in-person
19       001           1   01  Schleswig-Holstein          0      in-person

electionMethod
in-person    67021
postal       27647
Name: count, dtype: int64

## 4. Parteienfelder der Erst- und Zweitstimmen bestimmen

Die Spalten `E_Gültige`, `E_Ungültige`, `Z_Gültige` und `Z_Ungültige` sind Summen und keine Parteien. Alle übrigen `E_`- beziehungsweise `Z_`-Spalten bleiben erhalten.

In [8]:
first_vote_columns = district_party_columns(normalized_district_rows, "E_")
second_vote_columns = district_party_columns(normalized_district_rows, "Z_")

print(f"Erststimmen-Parteifelder: {len(first_vote_columns)}")
print(f"Zweitstimmen-Parteifelder: {len(second_vote_columns)}")
display(pd.Series(first_vote_columns, name="first vote columns").to_frame())
display(pd.Series(second_vote_columns, name="second vote columns").to_frame())

Erststimmen-Parteifelder: 45
Zweitstimmen-Parteifelder: 40

        first vote columns
0                    E_CDU
1                    E_SPD
2                    E_AfD
3                    E_FDP
4              E_DIE LINKE
5                  E_GRÜNE
6                    E_CSU
7           E_FREIE WÄHLER
8             E_Die PARTEI
9       E_Tierschutzpartei
10                   E_NPD
11               E_PIRATEN
12                   E_ÖDP
13             E_V-Partei³
14                   E_DiB
15                    E_BP
16     E_Tierschutzallianz
17                  E_MLPD
18  E_Gesundheitsforschung
19      E_MENSCHLICHE WELT
20                   E_DKP
21            E_Die Grauen
22                  E_BüSo
23        E_Die Humanisten
24          E_Gartenpartei
25                   E_du.
26              E_dieBasis
27             E_Bündnis C
28        E_BÜRGERBEWEGUNG
29              E_III. Weg
30             E_Bündnis21
31                 E_LIEBE
32                   E_LKR
33                   E_SSW
34       E_Team Todenhöfer
35           E_UNABHÄNGIGE
36                  E_Volt
37       E_Volksabstimmung
38                    E_B*
39              E_sonstige
40               E_FAMILIE
41         E_Graue Panther
42          E_KlimalisteBW
43                   E_THP
44                E_Übrige

       second vote columns
0                    Z_CDU
1                    Z_SPD
2                    Z_AfD
3                    Z_FDP
4              Z_DIE LINKE
5                  Z_GRÜNE
6                    Z_CSU
7           Z_FREIE WÄHLER
8             Z_Die PARTEI
9       Z_Tierschutzpartei
10                   Z_NPD
11               Z_PIRATEN
12                   Z_ÖDP
13             Z_V-Partei³
14                   Z_DiB
15                    Z_BP
16     Z_Tierschutzallianz
17                  Z_MLPD
18  Z_Gesundheitsforschung
19      Z_MENSCHLICHE WELT
20                   Z_DKP
21            Z_Die Grauen
22                  Z_BüSo
23        Z_Die Humanisten
24          Z_Gartenpartei
25                   Z_du.
26                   Z_SGP
27              Z_dieBasis
28             Z_Bündnis C
29        Z_BÜRGERBEWEGUNG
30              Z_III. Weg
31             Z_Bündnis21
32                 Z_LIEBE
33                   Z_LKR
34                   Z_PdF
35                   Z_LfK
36                   Z_SSW
37       Z_Team Todenhöfer
38           Z_UNABHÄNGIGE
39                  Z_Volt

## 5. Breite Parteispalten in einzelne Stimmenzeilen umformen

Jede Zeile beschreibt danach genau eine Kombination aus Quellzeile, Wahlkreis, Partei, Stimmenart und Brief-/Urnenwahl. Zu diesem Zeitpunkt liegen die Daten weiterhin auf Wahlbezirksebene vor.

In [9]:
first_polling_district_votes = reshape_polling_district_votes(
    normalized_district_rows,
    prefix="E_",
    vote_type="1",
)
second_polling_district_votes = reshape_polling_district_votes(
    normalized_district_rows,
    prefix="Z_",
    vote_type="2",
)

display(first_polling_district_votes.head(20))
display(second_polling_district_votes.head(20))

,sourceRow,districtId,state,party,voteType,electionMethod,votes
0,0,1,Schleswig-Holstein,AfD,1,in-person,38.0
1,1,1,Schleswig-Holstein,AfD,1,in-person,69.0
2,2,1,Schleswig-Holstein,AfD,1,in-person,44.0
3,3,1,Schleswig-Holstein,AfD,1,in-person,45.0
4,4,1,Schleswig-Holstein,AfD,1,in-person,41.0
5,5,1,Schleswig-Holstein,AfD,1,in-person,38.0
6,6,1,Schleswig-Holstein,AfD,1,in-person,37.0
7,7,1,Schleswig-Holstein,AfD,1,in-person,24.0
8,8,1,Schleswig-Holstein,AfD,1,in-person,24.0
9,9,1,Schleswig-Holstein,AfD,1,in-person,21.0
10,10,1,Schleswig-Holstein,AfD,1,in-person,31.0
11,11,1,Schleswig-Holstein,AfD,1,in-person,34.0
12,12,1,Schleswig-Holstein,AfD,1,in-person,35.0
13,13,1,Schleswig-Holstein,AfD,1,in-person,45.0
14,14,1,Schleswig-Holstein,AfD,1,in-person,47.0
15,15,1,Schleswig-Holstein,AfD,1,in-person,67.0
16,16,1,Schleswig-Holstein,AfD,1,in-person,63.0
17,17,1,Schleswig-Holstein,AfD,1,in-person,66.0
18,18,1,Schleswig-Holstein,AfD,1,in-person,68.0
19,19,1,Schleswig-Holstein,AfD,1,in-person,60.0

,sourceRow,districtId,state,party,voteType,electionMethod,votes
0,0,1,Schleswig-Holstein,AfD,2,in-person,35.0
1,1,1,Schleswig-Holstein,AfD,2,in-person,59.0
2,2,1,Schleswig-Holstein,AfD,2,in-person,42.0
3,3,1,Schleswig-Holstein,AfD,2,in-person,47.0
4,4,1,Schleswig-Holstein,AfD,2,in-person,34.0
5,5,1,Schleswig-Holstein,AfD,2,in-person,34.0
6,6,1,Schleswig-Holstein,AfD,2,in-person,38.0
7,7,1,Schleswig-Holstein,AfD,2,in-person,22.0
8,8,1,Schleswig-Holstein,AfD,2,in-person,27.0
9,9,1,Schleswig-Holstein,AfD,2,in-person,27.0
10,10,1,Schleswig-Holstein,AfD,2,in-person,32.0
11,11,1,Schleswig-Holstein,AfD,2,in-person,36.0
12,12,1,Schleswig-Holstein,AfD,2,in-person,42.0
13,13,1,Schleswig-Holstein,AfD,2,in-person,45.0
14,14,1,Schleswig-Holstein,AfD,2,in-person,52.0
15,15,1,Schleswig-Holstein,AfD,2,in-person,66.0
16,16,1,Schleswig-Holstein,AfD,2,in-person,62.0
17,17,1,Schleswig-Holstein,AfD,2,in-person,78.0
18,18,1,Schleswig-Holstein,AfD,2,in-person,70.0
19,19,1,Schleswig-Holstein,AfD,2,in-person,66.0

## 6. Wahlbezirke zu Wahlkreisen zusammenfassen

Für die App wird nicht jeder Wahlbezirk gespeichert. Alle Wahlbezirke desselben Wahlkreises werden nach Partei, Stimmenart und Brief-/Urnenwahl addiert.

In [10]:
polling_district_votes = pd.concat(
    [first_polling_district_votes, second_polling_district_votes],
    ignore_index=True,
)
district_totals = aggregate_to_constituencies(polling_district_votes)

print(f"Wahlkreise: {district_totals['districtId'].nunique()}")
print(f"Bundesländer: {district_totals['state'].nunique()}")
print(f"Parteien/Sammelkategorien: {district_totals['party'].nunique()}")
print(f"Wahlkreis-Summen-Zeilen: {len(district_totals):,}")
display(district_totals.head(30))

Wahlkreise: 299
Bundesländer: 16
Parteien/Sammelkategorien: 48
Wahlkreis-Summen-Zeilen: 20,579

,districtId,state,party,voteType,electionMethod,votes
0,1,Schleswig-Holstein,AfD,1,in-person,7936.0
1,1,Schleswig-Holstein,AfD,1,postal,1832.0
2,1,Schleswig-Holstein,AfD,2,in-person,8293.0
3,1,Schleswig-Holstein,AfD,2,postal,2024.0
4,1,Schleswig-Holstein,CDU,1,in-person,29743.0
5,1,Schleswig-Holstein,CDU,1,postal,11978.0
6,1,Schleswig-Holstein,CDU,2,in-person,25562.0
7,1,Schleswig-Holstein,CDU,2,postal,10859.0
8,1,Schleswig-Holstein,DIE LINKE,1,in-person,4701.0
9,1,Schleswig-Holstein,DIE LINKE,1,postal,1843.0
10,1,Schleswig-Holstein,DIE LINKE,2,in-person,5398.0
11,1,Schleswig-Holstein,DIE LINKE,2,postal,2077.0
12,1,Schleswig-Holstein,DKP,2,in-person,25.0
13,1,Schleswig-Holstein,DKP,2,postal,15.0
14,1,Schleswig-Holstein,Die Humanisten,2,in-person,114.0
15,1,Schleswig-Holstein,Die Humanisten,2,postal,43.0
16,1,Schleswig-Holstein,Die PARTEI,2,in-person,1352.0
17,1,Schleswig-Holstein,Die PARTEI,2,postal,492.0
18,1,Schleswig-Holstein,FDP,1,in-person,9034.0
19,1,Schleswig-Holstein,FDP,1,postal,3265.0
20,1,Schleswig-Holstein,FDP,2,in-person,13444.0
21,1,Schleswig-Holstein,FDP,2,postal,5745.0
22,1,Schleswig-Holstein,FREIE WÄHLER,1,in-person,1630.0
23,1,Schleswig-Holstein,FREIE WÄHLER,1,postal,694.0
24,1,Schleswig-Holstein,FREIE WÄHLER,2,in-person,1248.0
25,1,Schleswig-Holstein,FREIE WÄHLER,2,postal,467.0
26,1,Schleswig-Holstein,GRÜNE,1,in-person,31751.0
27,1,Schleswig-Holstein,GRÜNE,1,postal,18480.0
28,1,Schleswig-Holstein,GRÜNE,2,in-person,21390.0
29,1,Schleswig-Holstein,GRÜNE,2,postal,11910.0

In [11]:
sample_district_id = int(district_totals["districtId"].min())
display(
    district_totals[district_totals["districtId"] == sample_district_id]
    .sort_values(["voteType", "electionMethod", "votes"], ascending=[True, True, False])
    .head(40)
)

,districtId,state,party,voteType,electionMethod,votes
26,1,Schleswig-Holstein,GRÜNE,1,in-person,31751.0
4,1,Schleswig-Holstein,CDU,1,in-person,29743.0
38,1,Schleswig-Holstein,SPD,1,in-person,29588.0
42,1,Schleswig-Holstein,SSW,1,in-person,9280.0
18,1,Schleswig-Holstein,FDP,1,in-person,9034.0
0,1,Schleswig-Holstein,AfD,1,in-person,7936.0
8,1,Schleswig-Holstein,DIE LINKE,1,in-person,4701.0
54,1,Schleswig-Holstein,dieBasis,1,in-person,2526.0
22,1,Schleswig-Holstein,FREIE WÄHLER,1,in-person,1630.0
58,1,Schleswig-Holstein,du.,1,in-person,137.0
30,1,Schleswig-Holstein,LKR,1,in-person,102.0
27,1,Schleswig-Holstein,GRÜNE,1,postal,18480.0
5,1,Schleswig-Holstein,CDU,1,postal,11978.0
39,1,Schleswig-Holstein,SPD,1,postal,9339.0
43,1,Schleswig-Holstein,SSW,1,postal,3740.0
19,1,Schleswig-Holstein,FDP,1,postal,3265.0
9,1,Schleswig-Holstein,DIE LINKE,1,postal,1843.0
1,1,Schleswig-Holstein,AfD,1,postal,1832.0
55,1,Schleswig-Holstein,dieBasis,1,postal,831.0
23,1,Schleswig-Holstein,FREIE WÄHLER,1,postal,694.0
59,1,Schleswig-Holstein,du.,1,postal,90.0
31,1,Schleswig-Holstein,LKR,1,postal,55.0
40,1,Schleswig-Holstein,SPD,2,in-person,32901.0
6,1,Schleswig-Holstein,CDU,2,in-person,25562.0
28,1,Schleswig-Holstein,GRÜNE,2,in-person,21390.0
20,1,Schleswig-Holstein,FDP,2,in-person,13444.0
44,1,Schleswig-Holstein,SSW,2,in-person,12167.0
2,1,Schleswig-Holstein,AfD,2,in-person,8293.0
10,1,Schleswig-Holstein,DIE LINKE,2,in-person,5398.0
56,1,Schleswig-Holstein,dieBasis,2,in-person,2160.0
48,1,Schleswig-Holstein,Tierschutzpartei,2,in-person,1453.0
16,1,Schleswig-Holstein,Die PARTEI,2,in-person,1352.0
24,1,Schleswig-Holstein,FREIE WÄHLER,2,in-person,1248.0
52,1,Schleswig-Holstein,Volt,2,in-person,262.0
46,1,Schleswig-Holstein,Team Todenhöfer,2,in-person,238.0
14,1,Schleswig-Holstein,Die Humanisten,2,in-person,114.0
50,1,Schleswig-Holstein,V-Partei³,2,in-person,113.0
36,1,Schleswig-Holstein,NPD,2,in-person,106.0
60,1,Schleswig-Holstein,du.,2,in-person,78.0
62,1,Schleswig-Holstein,ÖDP,2,in-person,78.0

## 7. Repräsentative Landesstatistik unverändert einlesen

Die Kommentarzeilen am Anfang beginnen mit `#` und werden beim Einlesen übersprungen. Die eigentliche Tabelle bleibt ansonsten unverändert.

In [12]:
raw_state_statistics = read_local_csv(STATE_DEMOGRAPHICS_CSV, comment="#")
print(f"Zeilen: {len(raw_state_statistics):,}")
print(f"Spalten: {len(raw_state_statistics.columns):,}")
display(raw_state_statistics.head(20))

Zeilen: 798
Spalten: 16

,Land,Erst-/Zweitstimme,Geschlecht,Geburtsjahresgruppe,Summe,Ungültig,CDU,SPD,AfD,FDP,DIE LINKE,GRÜNE,CSU,Sonstige,dar. FREIE WÄHLER,dar. dieBasis
0,Bund,1,Summe,Summe,46854508,492495,10451524,12234690,4695611,4042951,2307536,6469081,2788048,3372572,1316686,734011
1,Bund,1,Summe,1997 – 2003,3524799,25512,434605,667343,218003,592862,276324,816458,132261,361432,106749,48258
2,Bund,1,Summe,1987 – 1996,5992701,44955,835239,1203503,588419,718457,407852,1289831,253494,650951,224446,111570
3,Bund,1,Summe,1977 – 1986,6466965,51452,1197212,1342590,880187,609213,323578,1081171,332210,649352,242994,155238
4,Bund,1,Summe,1962 – 1976,12604097,111747,2721637,3171648,1559505,1051192,523633,1738183,727673,998879,416490,257493
5,Bund,1,Summe,1952 – 1961,8435960,95625,1965006,2607468,882411,546049,394588,944474,553345,446994,205410,105472
6,Bund,1,Summe,1951 und früher,9829986,163203,3297825,3242137,567086,525178,381561,598964,789066,264964,120596,55981
7,Bund,1,m,Summe,22734708,220270,4982359,5737028,2854612,2110369,1107736,2831007,1344645,1546681,613091,294789
8,Bund,1,m,1997 – 2003,1771704,11797,226552,323416,132304,368718,114541,342015,70142,182219,52641,22052
9,Bund,1,m,1987 – 1996,3002958,22548,421268,584832,348089,416227,199337,557623,130911,322122,107029,47848
10,Bund,1,m,1977 – 1986,3206665,23389,585876,627164,540189,314688,160716,486298,163113,305233,113905,64151
11,Bund,1,m,1962 – 1976,6242161,51397,1388481,1502373,971810,513769,251947,757532,366112,438740,193687,101234
12,Bund,1,m,1952 – 1961,4138983,44379,936097,1262999,532726,266245,194510,428381,275965,197682,97385,41015
13,Bund,1,m,1951 und früher,4372237,66761,1424086,1436243,329494,230722,186686,259160,338401,100685,48443,18490
14,Bund,1,w,Summe,24119800,272225,5469165,6497662,1840999,1932582,1199800,3638074,1443403,1825891,703595,439222
15,Bund,1,w,1997 – 2003,1753095,13715,208053,343926,85699,224144,161783,474443,62118,179212,54108,26206
16,Bund,1,w,1987 – 1996,2989744,22407,413971,618671,240330,302229,208514,732208,122583,328829,117417,63722
17,Bund,1,w,1977 – 1986,3260299,28063,611336,715426,339998,294526,162862,594873,169097,344119,129090,91087
18,Bund,1,w,1962 – 1976,6361936,60350,1333156,1669275,587694,537423,271686,980652,361561,560139,222803,156260
19,Bund,1,w,1952 – 1961,4296976,51247,1028908,1344468,349685,279804,200079,516093,277380,249313,108024,64457

## 8. Dimensionen der Statistik vereinheitlichen

Bundesland, Erst-/Zweitstimme, Geschlecht und Altersgruppe erhalten die Werte, die später auch im JSON stehen. Summenzeilen bleiben zunächst erhalten und sind an leeren normalisierten Dimensionen erkennbar.

In [13]:
normalized_state_statistics = normalize_state_statistic_rows(raw_state_statistics)

display(
    normalized_state_statistics[
        [
            "Land",
            "state",
            "Erst-/Zweitstimme",
            "voteType",
            "Geschlecht",
            "gender",
            "Geburtsjahresgruppe",
            "ageGroup",
        ]
    ].head(30)
)

,Land,state,Erst-/Zweitstimme,voteType,Geschlecht,gender,Geburtsjahresgruppe,ageGroup
0,Bund,None,1,1,Summe,None,Summe,None
1,Bund,None,1,1,Summe,None,1997 – 2003,18-24
2,Bund,None,1,1,Summe,None,1987 – 1996,25-34
3,Bund,None,1,1,Summe,None,1977 – 1986,35-44
4,Bund,None,1,1,Summe,None,1962 – 1976,45-54
5,Bund,None,1,1,Summe,None,1952 – 1961,55-64
6,Bund,None,1,1,Summe,None,1951 und früher,65+
7,Bund,None,1,1,m,m,Summe,None
8,Bund,None,1,1,m,m,1997 – 2003,18-24
9,Bund,None,1,1,m,m,1987 – 1996,25-34
10,Bund,None,1,1,m,m,1977 – 1986,35-44
11,Bund,None,1,1,m,m,1962 – 1976,45-54
12,Bund,None,1,1,m,m,1952 – 1961,55-64
13,Bund,None,1,1,m,m,1951 und früher,65+
14,Bund,None,1,1,w,w,Summe,None
15,Bund,None,1,1,w,w,1997 – 2003,18-24
16,Bund,None,1,1,w,w,1987 – 1996,25-34
17,Bund,None,1,1,w,w,1977 – 1986,35-44
18,Bund,None,1,1,w,w,1962 – 1976,45-54
19,Bund,None,1,1,w,w,1952 – 1961,55-64
20,Bund,None,1,1,w,w,1951 und früher,65+
21,Bund,None,2,2,Summe,None,Summe,None
22,Bund,None,2,2,Summe,None,1997 – 2003,18-24
23,Bund,None,2,2,Summe,None,1987 – 1996,25-34
24,Bund,None,2,2,Summe,None,1977 – 1986,35-44
25,Bund,None,2,2,Summe,None,1962 – 1976,45-54
26,Bund,None,2,2,Summe,None,1952 – 1961,55-64
27,Bund,None,2,2,Summe,None,1951 und früher,65+
28,Bund,None,2,2,m,m,Summe,None
29,Bund,None,2,2,m,m,1997 – 2003,18-24

Die folgenden Zeilen sind Bundes-, Geschlechts-, Alters- oder andere Summen. Sie werden angezeigt, bevor sie für die Detailverteilung entfernt werden.

In [14]:
statistic_dimensions = ["state", "voteType", "gender", "ageGroup"]
summary_statistic_rows = normalized_state_statistics[
    ~normalized_state_statistics[statistic_dimensions].notna().all(axis=1)
]
print(f"Ausgeschlossene Summenzeilen: {len(summary_statistic_rows):,}")
display(
    summary_statistic_rows[
        ["Land", "Erst-/Zweitstimme", "Geschlecht", "Geburtsjahresgruppe"]
    ].head(50)
)

Ausgeschlossene Summenzeilen: 414

    Land Erst-/Zweitstimme Geschlecht Geburtsjahresgruppe
0   Bund                 1      Summe               Summe
1   Bund                 1      Summe         1997 – 2003
2   Bund                 1      Summe         1987 – 1996
3   Bund                 1      Summe         1977 – 1986
4   Bund                 1      Summe         1962 – 1976
5   Bund                 1      Summe         1952 – 1961
6   Bund                 1      Summe     1951 und früher
7   Bund                 1          m               Summe
8   Bund                 1          m         1997 – 2003
9   Bund                 1          m         1987 – 1996
10  Bund                 1          m         1977 – 1986
11  Bund                 1          m         1962 – 1976
12  Bund                 1          m         1952 – 1961
13  Bund                 1          m     1951 und früher
14  Bund                 1          w               Summe
15  Bund                 1          w         1997 – 2003
16  Bund                 1          w         1987 – 1996
17  Bund                 1          w         1977 – 1986
18  Bund                 1          w         1962 – 1976
19  Bund                 1          w         1952 – 1961
20  Bund                 1          w     1951 und früher
21  Bund                 2      Summe               Summe
22  Bund                 2      Summe         1997 – 2003
23  Bund                 2      Summe         1987 – 1996
24  Bund                 2      Summe         1977 – 1986
25  Bund                 2      Summe         1962 – 1976
26  Bund                 2      Summe         1952 – 1961
27  Bund                 2      Summe     1951 und früher
28  Bund                 2          m               Summe
29  Bund                 2          m         1997 – 2003
30  Bund                 2          m         1987 – 1996
31  Bund                 2          m         1977 – 1986
32  Bund                 2          m         1962 – 1976
33  Bund                 2          m         1952 – 1961
34  Bund                 2          m     1951 und früher
35  Bund                 2          w               Summe
36  Bund                 2          w         1997 – 2003
37  Bund                 2          w         1987 – 1996
38  Bund                 2          w         1977 – 1986
39  Bund                 2          w         1962 – 1976
40  Bund                 2          w         1952 – 1961
41  Bund                 2          w     1951 und früher
42    SH                 1      Summe               Summe
43    SH                 1      Summe         1997 – 2003
44    SH                 1      Summe         1987 – 1996
45    SH                 1      Summe         1977 – 1986
46    SH                 1      Summe         1962 – 1976
47    SH                 1      Summe         1952 – 1961
48    SH                 1      Summe     1951 und früher
49    SH                 1          m               Summe

In [15]:
state_statistic_details = select_state_statistic_detail_rows(
    normalized_state_statistics
)
print(f"Verwendete Detailzeilen: {len(state_statistic_details):,}")
display(state_statistic_details.head(20))

Verwendete Detailzeilen: 384

,Land,Erst-/Zweitstimme,Geschlecht,Geburtsjahresgruppe,Summe,Ungültig,CDU,SPD,AfD,FDP,DIE LINKE,GRÜNE,CSU,Sonstige,dar. FREIE WÄHLER,dar. dieBasis,state,voteType,gender,ageGroup
50,SH,1,m,1997 – 2003,66529,694,9478,12901,3319,14435,3857,16164,,5681,863,554,Schleswig-Holstein,1,m,18-24
51,SH,1,m,1987 – 1996,96579,578,14851,20904,10100,15494,5186,20209,,9256,1683,1519,Schleswig-Holstein,1,m,25-34
52,SH,1,m,1977 – 1986,107371,549,23770,27281,13607,10462,4101,17679,,9922,2686,2488,Schleswig-Holstein,1,m,35-44
53,SH,1,m,1962 – 1976,245329,1772,66001,68443,24942,22852,6835,37377,,17108,4746,3984,Schleswig-Holstein,1,m,45-54
54,SH,1,m,1952 – 1961,150261,1634,38538,52157,11096,10622,3944,24632,,7639,2138,1747,Schleswig-Holstein,1,m,55-64
55,SH,1,m,1951 und früher,189819,2868,75673,65744,7620,13152,2630,18538,,3594,781,587,Schleswig-Holstein,1,m,65+
57,SH,1,w,1997 – 2003,65832,349,7852,13255,1893,9861,4674,22686,,5263,1255,864,Schleswig-Holstein,1,w,18-24
58,SH,1,w,1987 – 1996,99872,629,15001,26221,8045,10762,5318,25015,,8881,2287,1897,Schleswig-Holstein,1,w,25-34
59,SH,1,w,1977 – 1986,121165,650,26874,32453,7574,11222,4495,25966,,11933,3261,3107,Schleswig-Holstein,1,w,35-44
60,SH,1,w,1962 – 1976,255806,1541,61120,75089,13327,23409,8519,52590,,20211,4930,6486,Schleswig-Holstein,1,w,45-54
61,SH,1,w,1952 – 1961,156623,1153,38228,55563,7067,11338,3926,31921,,7427,1745,2684,Schleswig-Holstein,1,w,55-64
62,SH,1,w,1951 und früher,220958,3716,88588,80288,5052,13583,2038,22858,,4834,1075,1529,Schleswig-Holstein,1,w,65+
71,SH,2,m,1997 – 2003,66529,593,5550,11466,3653,17629,4253,14872,,8512,527,349,Schleswig-Holstein,2,m,18-24
72,SH,2,m,1987 – 1996,96579,390,11268,17128,10723,18734,5871,19996,,12469,1155,929,Schleswig-Holstein,2,m,25-34
73,SH,2,m,1977 – 1986,107371,414,17920,23417,13783,14787,4559,20032,,12458,1570,2390,Schleswig-Holstein,2,m,35-44
74,SH,2,m,1962 – 1976,245329,1154,53882,64224,25932,31064,7755,40332,,20986,3108,3057,Schleswig-Holstein,2,m,45-54
75,SH,2,m,1952 – 1961,150261,1307,32503,49395,11444,15210,5993,25324,,9086,1347,1651,Schleswig-Holstein,2,m,55-64
76,SH,2,m,1951 und früher,189819,2523,65610,63747,8461,21407,3609,18770,,5693,463,403,Schleswig-Holstein,2,m,65+
78,SH,2,w,1997 – 2003,65832,276,5302,11094,2506,11224,5644,20965,,8821,918,449,Schleswig-Holstein,2,w,18-24
79,SH,2,w,1987 – 1996,99872,628,11560,20824,7678,12733,5263,25373,,15813,1609,1783,Schleswig-Holstein,2,w,25-34

## 9. Statistik in lange Parteizeilen umformen

Die veröffentlichten absoluten Statistikwerte werden zunächst nur umgeformt. Noch werden sie nicht als amtliche Stimmenzahlen verwendet.

In [16]:
state_statistic_votes = reshape_state_statistic_votes(state_statistic_details)
print(f"Statistikzellen: {len(state_statistic_votes):,}")
display(state_statistic_votes.head(30))

Statistikzellen: 3,840

                state voteType party gender ageGroup  statisticVotes
0   Baden-Württemberg        1   AfD      m    18-24         17085.0
1   Baden-Württemberg        1   AfD      m    25-34         44896.0
2   Baden-Württemberg        1   AfD      m    35-44         63967.0
3   Baden-Württemberg        1   AfD      m    45-54        119694.0
4   Baden-Württemberg        1   AfD      m    55-64         61079.0
5   Baden-Württemberg        1   AfD      m      65+         38239.0
6   Baden-Württemberg        1   AfD      w    18-24          8893.0
7   Baden-Württemberg        1   AfD      w    25-34         29727.0
8   Baden-Württemberg        1   AfD      w    35-44         39304.0
9   Baden-Württemberg        1   AfD      w    45-54         70848.0
10  Baden-Württemberg        1   AfD      w    55-64         41970.0
11  Baden-Württemberg        1   AfD      w      65+         25356.0
12  Baden-Württemberg        1   CDU      m    18-24         41235.0
13  Baden-Württemberg        1   CDU      m    25-34         82190.0
14  Baden-Württemberg        1   CDU      m    35-44        103535.0
15  Baden-Württemberg        1   CDU      m    45-54        238508.0
16  Baden-Württemberg        1   CDU      m    55-64        159810.0
17  Baden-Württemberg        1   CDU      m      65+        236310.0
18  Baden-Württemberg        1   CDU      w    18-24         38331.0
19  Baden-Württemberg        1   CDU      w    25-34         80399.0
20  Baden-Württemberg        1   CDU      w    35-44        100391.0
21  Baden-Württemberg        1   CDU      w    45-54        223146.0
22  Baden-Württemberg        1   CDU      w    55-64        170339.0
23  Baden-Württemberg        1   CDU      w      65+        293123.0
24  Baden-Württemberg        1   CSU      m    18-24             0.0
25  Baden-Württemberg        1   CSU      m    25-34             0.0
26  Baden-Württemberg        1   CSU      m    35-44             0.0
27  Baden-Württemberg        1   CSU      m    45-54             0.0
28  Baden-Württemberg        1   CSU      m    55-64             0.0
29  Baden-Württemberg        1   CSU      m      65+             0.0

## 10. Gerundete Statistikwerte in Anteile umrechnen

Die repräsentative Statistik kann durch Rundung und Methodik vom amtlichen Endergebnis abweichen. Deshalb wird jede Zelle durch die statistische Summe ihrer Partei im jeweiligen Land und für die jeweilige Stimmenart geteilt.

Diese Anteile werden später mit den amtlichen Wahlkreis- und Wahlartsummen multipliziert. Die absoluten Statistikwerte werden also nicht als Endsumme übernommen.

In [17]:
demographic_profiles = calculate_demographic_profiles(state_statistic_votes)

display(demographic_profiles.head(30))

share_checks = (
    demographic_profiles.groupby(["state", "voteType", "party"])["share"]
    .sum()
    .sub(1.0)
    .abs()
)
print(f"Größte Abweichung einer Anteils-Summe von 1: {share_checks.max():.12g}")

,state,voteType,party,gender,ageGroup,statisticVotes,statisticTotal,share
0,Baden-Württemberg,1,AfD,m,18-24,17085.0,561058.0,0.030451
1,Baden-Württemberg,1,AfD,m,25-34,44896.0,561058.0,0.080020
2,Baden-Württemberg,1,AfD,m,35-44,63967.0,561058.0,0.114011
3,Baden-Württemberg,1,AfD,m,45-54,119694.0,561058.0,0.213336
4,Baden-Württemberg,1,AfD,m,55-64,61079.0,561058.0,0.108864
5,Baden-Württemberg,1,AfD,m,65+,38239.0,561058.0,0.068155
6,Baden-Württemberg,1,AfD,w,18-24,8893.0,561058.0,0.015850
7,Baden-Württemberg,1,AfD,w,25-34,29727.0,561058.0,0.052984
8,Baden-Württemberg,1,AfD,w,35-44,39304.0,561058.0,0.070053
9,Baden-Württemberg,1,AfD,w,45-54,70848.0,561058.0,0.126276
10,Baden-Württemberg,1,AfD,w,55-64,41970.0,561058.0,0.074805
11,Baden-Württemberg,1,AfD,w,65+,25356.0,561058.0,0.045193
12,Baden-Württemberg,1,CDU,m,18-24,41235.0,1767317.0,0.023332
13,Baden-Württemberg,1,CDU,m,25-34,82190.0,1767317.0,0.046506
14,Baden-Württemberg,1,CDU,m,35-44,103535.0,1767317.0,0.058583
15,Baden-Württemberg,1,CDU,m,45-54,238508.0,1767317.0,0.134955
16,Baden-Württemberg,1,CDU,m,55-64,159810.0,1767317.0,0.090425
17,Baden-Württemberg,1,CDU,m,65+,236310.0,1767317.0,0.133711
18,Baden-Württemberg,1,CDU,w,18-24,38331.0,1767317.0,0.021689
19,Baden-Württemberg,1,CDU,w,25-34,80399.0,1767317.0,0.045492
20,Baden-Württemberg,1,CDU,w,35-44,100391.0,1767317.0,0.056804
21,Baden-Württemberg,1,CDU,w,45-54,223146.0,1767317.0,0.126263
22,Baden-Württemberg,1,CDU,w,55-64,170339.0,1767317.0,0.096383
23,Baden-Württemberg,1,CDU,w,65+,293123.0,1767317.0,0.165858
24,Baden-Württemberg,1,DIE LINKE,m,18-24,10894.0,175692.0,0.062006
25,Baden-Württemberg,1,DIE LINKE,m,25-34,18259.0,175692.0,0.103926
26,Baden-Württemberg,1,DIE LINKE,m,35-44,13236.0,175692.0,0.075336
27,Baden-Württemberg,1,DIE LINKE,m,45-54,20710.0,175692.0,0.117877
28,Baden-Württemberg,1,DIE LINKE,m,55-64,12895.0,175692.0,0.073395
29,Baden-Württemberg,1,DIE LINKE,m,65+,6939.0,175692.0,0.039495

Größte Abweichung einer Anteils-Summe von 1: 0

In [18]:
# Beispiel: veröffentlichte statistische Summe und amtliche Summe nebeneinander.
statistic_totals = (
    demographic_profiles[["state", "voteType", "party", "statisticTotal"]]
    .drop_duplicates()
)
official_totals = (
    district_totals.groupby(["state", "voteType", "party"], as_index=False)["votes"]
    .sum()
    .rename(columns={"votes": "officialTotal"})
)
total_comparison = official_totals.merge(
    statistic_totals,
    on=["state", "voteType", "party"],
    how="inner",
)
total_comparison["difference"] = (
    total_comparison["officialTotal"] - total_comparison["statisticTotal"]
)
display(total_comparison.reindex(total_comparison["difference"].abs().sort_values(ascending=False).index).head(30))

,state,voteType,party,officialTotal,statisticTotal,difference
39,Berlin,1,Sonstige,251.0,145636.0,-145385.0
47,Berlin,2,SPD,374413.0,428288.0,-53875.0
38,Berlin,1,SPD,366569.0,417161.0,-50592.0
46,Berlin,2,GRÜNE,370735.0,408531.0,-37796.0
37,Berlin,1,GRÜNE,346880.0,380581.0,-33701.0
44,Berlin,2,FDP,136998.0,165936.0,-28938.0
35,Berlin,1,FDP,106292.0,129678.0,-23386.0
34,Berlin,1,DIE LINKE,238776.0,260243.0,-21467.0
43,Berlin,2,DIE LINKE,194010.0,209053.0,-15043.0
20,Bayern,1,FREIE WÄHLER,587357.0,577845.0,9512.0
4,Baden-Württemberg,1,FREIE WÄHLER,143422.0,137485.0,5937.0
33,Berlin,1,CDU,339234.0,344838.0,-5604.0
41,Berlin,2,AfD,159025.0,153695.0,5330.0
32,Berlin,1,AfD,151449.0,147134.0,4315.0
100,Hessen,1,FREIE WÄHLER,81432.0,77360.0,4072.0
40,Berlin,1,dieBasis,16770.0,19600.0,-2830.0
52,Brandenburg,1,FREIE WÄHLER,47029.0,49310.0,-2281.0
151,Nordrhein-Westfalen,1,dieBasis,111606.0,109355.0,2251.0
45,Berlin,2,FREIE WÄHLER,14953.0,17069.0,-2116.0
36,Berlin,1,FREIE WÄHLER,12134.0,14162.0,-2028.0
243,Thüringen,1,FREIE WÄHLER,31190.0,29632.0,1558.0
164,Rheinland-Pfalz,1,FREIE WÄHLER,116525.0,114991.0,1534.0
211,Sachsen-Anhalt,1,FREIE WÄHLER,32152.0,33554.0,-1402.0
227,Schleswig-Holstein,1,FREIE WÄHLER,26518.0,27450.0,-932.0
23,Bayern,1,dieBasis,156556.0,157440.0,-884.0
87,Hamburg,1,dieBasis,17259.0,16396.0,863.0
132,Niedersachsen,1,FREIE WÄHLER,47466.0,46687.0,779.0
116,Mecklenburg-Vorpommern,1,FREIE WÄHLER,17781.0,18484.0,-703.0
119,Mecklenburg-Vorpommern,1,dieBasis,16019.0,15415.0,604.0
198,Sachsen,1,dieBasis,45593.0,45040.0,553.0

## 11. Optionales Bundesmuster für Brief- und Urnenwahl

Diese dritte Datei ist nicht pro Wahlkreis. Sie enthält ein bundesweites Muster nach Partei, Geschlecht, Alter und Brief-/Urnenwahl. IPF benutzt es nur als Ausgangsmuster.

Ist kein Pfad eingetragen, wird ein neutrales Ausgangsmuster verwendet. Die bekannten Landesränder werden in beiden Fällen exakt angepasst.

In [19]:
federal_method_seed = None

if FEDERAL_METHOD_DEMOGRAPHICS_CSV is None:
    print("Keine optionale Bundesdatei angegeben. Es wird ein neutrales Ausgangsmuster verwendet.")
else:
    raw_federal_method_statistics = read_local_csv(
        FEDERAL_METHOD_DEMOGRAPHICS_CSV,
        comment="#",
    )
    display(raw_federal_method_statistics.head(20))

    normalized_federal_method_statistics = normalize_federal_method_rows(
        raw_federal_method_statistics
    )
    display(normalized_federal_method_statistics.head(20))

    federal_method_details = select_federal_method_detail_rows(
        normalized_federal_method_statistics
    )
    federal_method_votes = reshape_federal_method_votes(federal_method_details)
    display(federal_method_votes.head(30))

    federal_method_seed = calculate_federal_method_weights(federal_method_votes)
    display(federal_method_seed.head(30))

Keine optionale Bundesdatei angegeben. Es wird ein neutrales Ausgangsmuster verwendet.

## 12. Landesprofile mit IPF berechnen

Für jede Partei und Stimmenart werden zwei bekannte Ränder zusammengeführt:

- die demografischen Anteile aus der Landesstatistik;
- die amtlichen Brief- und Urnenstimmen aus der Wahlbezirksdatei.

Parteien ohne eigene Statistik verwenden das Profil von `Sonstige`. Nur wenn auch dieses fehlt, wird gleichverteilt.

In [20]:
state_method_profiles = build_state_method_profiles(
    district_totals,
    demographic_profiles,
    federal_method_seed,
)

print(f"Profilzeilen: {len(state_method_profiles):,}")
display(
    state_method_profiles[
        ["party", "demographicProfileSource", "methodSeedSource"]
    ].drop_duplicates().sort_values(["demographicProfileSource", "party"])
)
display(state_method_profiles.head(30))

Profilzeilen: 15,288

,party,demographicProfileSource,methodSeedSource
2400,B*,other-statistics,independent-method-fallback
1176,BP,other-statistics,independent-method-fallback
600,BÜNDNIS21,other-statistics,independent-method-fallback
24,BÜRGERBEWEGUNG,other-statistics,independent-method-fallback
48,BüSo,other-statistics,independent-method-fallback
72,Bündnis C,other-statistics,independent-method-fallback
720,DKP,other-statistics,independent-method-fallback
144,DiB,other-statistics,independent-method-fallback
2496,Die Grauen,other-statistics,independent-method-fallback
168,Die Humanisten,other-statistics,independent-method-fallback
192,Die PARTEI,other-statistics,independent-method-fallback
3696,FAMILIE,other-statistics,independent-method-fallback
12888,Gartenpartei,other-statistics,independent-method-fallback
888,Gesundheitsforschung,other-statistics,independent-method-fallback
14616,Graue Panther,other-statistics,independent-method-fallback
2040,III. Weg,other-statistics,independent-method-fallback
288,Klimaliste BW,other-statistics,independent-method-fallback
9168,LIEBE,other-statistics,independent-method-fallback
312,LKR,other-statistics,independent-method-fallback
9792,LfK,other-statistics,independent-method-fallback
336,MENSCHLICHE WELT,other-statistics,independent-method-fallback
360,MLPD,other-statistics,independent-method-fallback
960,NPD,other-statistics,independent-method-fallback
384,PIRATEN,other-statistics,independent-method-fallback
9888,PdF,other-statistics,independent-method-fallback
3360,SGP,other-statistics,independent-method-fallback
13800,SSW,other-statistics,independent-method-fallback
14736,THP,other-statistics,independent-method-fallback
1032,Team Todenhöfer,other-statistics,independent-method-fallback
12960,Tierschutzallianz,other-statistics,independent-method-fallback
432,Tierschutzpartei,other-statistics,independent-method-fallback
1584,UNABHÄNGIGE,other-statistics,independent-method-fallback
456,V-Partei³,other-statistics,independent-method-fallback
9360,Volksabstimmung,other-statistics,independent-method-fallback
480,Volt,other-statistics,independent-method-fallback
1680,du.,other-statistics,independent-method-fallback
528,ÖDP,other-statistics,independent-method-fallback
552,Übrige,other-statistics,independent-method-fallback
0,AfD,party-statistics,independent-method-fallback
96,CDU,party-statistics,independent-method-fallback
1248,CSU,party-statistics,independent-method-fallback
120,DIE LINKE,party-statistics,independent-method-fallback
216,FDP,party-statistics,independent-method-fallback
240,FREIE WÄHLER,party-statistics,independent-method-fallback
264,GRÜNE,party-statistics,independent-method-fallback
408,SPD,party-statistics,independent-method-fallback
2784,Sonstige,party-statistics,independent-method-fallback
504,dieBasis,party-statistics,independent-method-fallback

,state,voteType,party,electionMethod,gender,ageGroup,share,stateMethodVotes,fittedStateVotes,demographicProfileSource,methodSeedSource
0,Baden-Württemberg,1,AfD,in-person,m,18-24,0.030451,369063.0,11238.483998,party-statistics,independent-method-fallback
1,Baden-Württemberg,1,AfD,in-person,m,25-34,0.080020,369063.0,29532.512589,party-statistics,independent-method-fallback
2,Baden-Württemberg,1,AfD,in-person,m,35-44,0.114011,369063.0,42077.384016,party-statistics,independent-method-fallback
3,Baden-Württemberg,1,AfD,in-person,m,45-54,0.213336,369063.0,78734.510019,party-statistics,independent-method-fallback
4,Baden-Württemberg,1,AfD,in-person,m,55-64,0.108864,369063.0,40177.662518,party-statistics,independent-method-fallback
5,Baden-Württemberg,1,AfD,in-person,m,65+,0.068155,369063.0,25153.549289,party-statistics,independent-method-fallback
6,Baden-Württemberg,1,AfD,in-person,w,18-24,0.015850,369063.0,5849.800304,party-statistics,independent-method-fallback
7,Baden-Württemberg,1,AfD,in-person,w,25-34,0.052984,369063.0,19554.370138,party-statistics,independent-method-fallback
8,Baden-Württemberg,1,AfD,in-person,w,35-44,0.070053,369063.0,25854.104481,party-statistics,independent-method-fallback
9,Baden-Württemberg,1,AfD,in-person,w,45-54,0.126276,369063.0,46603.694135,party-statistics,independent-method-fallback
10,Baden-Württemberg,1,AfD,in-person,w,55-64,0.074805,369063.0,27607.794756,party-statistics,independent-method-fallback
11,Baden-Württemberg,1,AfD,in-person,w,65+,0.045193,369063.0,16679.133758,party-statistics,independent-method-fallback
12,Baden-Württemberg,1,AfD,postal,m,18-24,0.030451,191995.0,5846.516002,party-statistics,independent-method-fallback
13,Baden-Württemberg,1,AfD,postal,m,25-34,0.080020,191995.0,15363.487411,party-statistics,independent-method-fallback
14,Baden-Württemberg,1,AfD,postal,m,35-44,0.114011,191995.0,21889.615984,party-statistics,independent-method-fallback
15,Baden-Württemberg,1,AfD,postal,m,45-54,0.213336,191995.0,40959.489981,party-statistics,independent-method-fallback
16,Baden-Württemberg,1,AfD,postal,m,55-64,0.108864,191995.0,20901.337482,party-statistics,independent-method-fallback
17,Baden-Württemberg,1,AfD,postal,m,65+,0.068155,191995.0,13085.450711,party-statistics,independent-method-fallback
18,Baden-Württemberg,1,AfD,postal,w,18-24,0.015850,191995.0,3043.199696,party-statistics,independent-method-fallback
19,Baden-Württemberg,1,AfD,postal,w,25-34,0.052984,191995.0,10172.629862,party-statistics,independent-method-fallback
20,Baden-Württemberg,1,AfD,postal,w,35-44,0.070053,191995.0,13449.895519,party-statistics,independent-method-fallback
21,Baden-Württemberg,1,AfD,postal,w,45-54,0.126276,191995.0,24244.305865,party-statistics,independent-method-fallback
22,Baden-Württemberg,1,AfD,postal,w,55-64,0.074805,191995.0,14362.205244,party-statistics,independent-method-fallback
23,Baden-Württemberg,1,AfD,postal,w,65+,0.045193,191995.0,8676.866242,party-statistics,independent-method-fallback
24,Baden-Württemberg,1,BÜRGERBEWEGUNG,in-person,m,18-24,0.062746,648.0,40.659234,other-statistics,independent-method-fallback
25,Baden-Württemberg,1,BÜRGERBEWEGUNG,in-person,m,25-34,0.101897,648.0,66.028946,other-statistics,independent-method-fallback
26,Baden-Württemberg,1,BÜRGERBEWEGUNG,in-person,m,35-44,0.092651,648.0,60.038063,other-statistics,independent-method-fallback
27,Baden-Württemberg,1,BÜRGERBEWEGUNG,in-person,m,45-54,0.124601,648.0,80.741534,other-statistics,independent-method-fallback
28,Baden-Württemberg,1,BÜRGERBEWEGUNG,in-person,m,55-64,0.046535,648.0,30.154419,other-statistics,independent-method-fallback
29,Baden-Württemberg,1,BÜRGERBEWEGUNG,in-person,m,65+,0.026432,648.0,17.128018,other-statistics,independent-method-fallback

## 13. Landesprofile auf die amtlichen Wahlkreissummen anwenden

Nun gilt für jede Wahlkreis-Partei-Wahlart-Kombination:

`geschätzte Stimmen = amtliche Wahlkreissumme × berechneter Profilanteil`

Die Summe aller erzeugten Detailzeilen bleibt dabei gleich der amtlichen Ausgangssumme.

In [21]:
first_district_totals = district_totals[district_totals["voteType"] == "1"].copy()
second_district_totals = district_totals[district_totals["voteType"] == "2"].copy()

first_votes = distribute_district_votes(first_district_totals, state_method_profiles)
second_votes = distribute_district_votes(second_district_totals, state_method_profiles)
all_votes = [*first_votes, *second_votes]

print(f"Erststimmen-Einträge: {len(first_votes):,}")
print(f"Zweitstimmen-Einträge: {len(second_votes):,}")
display(pd.DataFrame([asdict(entry) for entry in first_votes[:30]]))

Erststimmen-Einträge: 79,152
Zweitstimmen-Einträge: 167,796

,districtId,state,gender,ageGroup,party,voteType,electionMethod,votes
0,1,Schleswig-Holstein,m,18-24,AfD,1,in-person,231.776843
1,1,Schleswig-Holstein,m,25-34,AfD,1,in-person,705.316696
2,1,Schleswig-Holstein,m,35-44,AfD,1,in-person,950.222207
3,1,Schleswig-Holstein,m,45-54,AfD,1,in-person,1741.783073
4,1,Schleswig-Holstein,m,55-64,AfD,1,in-person,774.870699
5,1,Schleswig-Holstein,m,65+,AfD,1,in-person,532.130022
6,1,Schleswig-Holstein,w,18-24,AfD,1,in-person,132.194506
7,1,Schleswig-Holstein,w,25-34,AfD,1,in-person,561.809190
8,1,Schleswig-Holstein,w,35-44,AfD,1,in-person,528.917689
9,1,Schleswig-Holstein,w,45-54,AfD,1,in-person,930.668872
10,1,Schleswig-Holstein,w,55-64,AfD,1,in-person,493.512187
11,1,Schleswig-Holstein,w,65+,AfD,1,in-person,352.798015
12,1,Schleswig-Holstein,m,18-24,AfD,1,postal,53.504937
13,1,Schleswig-Holstein,m,25-34,AfD,1,postal,162.820084
14,1,Schleswig-Holstein,m,35-44,AfD,1,postal,219.355731
15,1,Schleswig-Holstein,m,45-54,AfD,1,postal,402.085004
16,1,Schleswig-Holstein,m,55-64,AfD,1,postal,178.876401
17,1,Schleswig-Holstein,m,65+,AfD,1,postal,122.840499
18,1,Schleswig-Holstein,w,18-24,AfD,1,postal,30.516675
19,1,Schleswig-Holstein,w,25-34,AfD,1,postal,129.691839
20,1,Schleswig-Holstein,w,35-44,AfD,1,postal,122.098942
21,1,Schleswig-Holstein,w,45-54,AfD,1,postal,214.841907
22,1,Schleswig-Holstein,w,55-64,AfD,1,postal,113.925696
23,1,Schleswig-Holstein,w,65+,AfD,1,postal,81.442284
24,1,Schleswig-Holstein,m,18-24,CDU,1,in-person,604.978291
25,1,Schleswig-Holstein,m,25-34,CDU,1,in-person,947.935492
26,1,Schleswig-Holstein,m,35-44,CDU,1,in-person,1517.232957
27,1,Schleswig-Holstein,m,45-54,CDU,1,in-person,4212.826774
28,1,Schleswig-Holstein,m,55-64,CDU,1,in-person,2459.870581
29,1,Schleswig-Holstein,m,65+,CDU,1,in-person,4830.188034

## 14. Bekannte Summen prüfen

Die Validierung vergleicht die erzeugten Einträge wieder mit den amtlichen Wahlkreis-/Wahlartsummen und mit den berechneten demografischen Landesrändern.

In [22]:
validation = validate_vote_entries(
    all_votes,
    district_totals,
    state_method_profiles,
)
validation

ValidationReport(entryCount=246948, sourceGroupCount=20579, maxDistrictMethodError=4.547473508864641e-13, maxStateDemographicError=3.703746642713668e-09)

## 15. JSON-Dateien schreiben

Erst nach allen sichtbaren Prüfungen werden die beiden Dateien gespeichert.

In [23]:
first_votes_path = write_vote_entries(
    first_votes,
    OUTPUT_DIRECTORY / "first_votes.json",
)
second_votes_path = write_vote_entries(
    second_votes,
    OUTPUT_DIRECTORY / "second_votes.json",
)

first_votes_path, second_votes_path

(PosixPath('/home/nomikron/WebstormProjects/mach-dir-dein-bundestag/scripts/data/generated/first_votes.json'),
 PosixPath('/home/nomikron/WebstormProjects/mach-dir-dein-bundestag/scripts/data/generated/second_votes.json'))